categories:
  - title: 'Features and Enhancements'
    labels:
      - 'feature'
      - 'perf'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
  - title: 'Maintenance'
    labels: 
      - 'build'
      - 'chore'
      - 'ci'
      - 'docs'
      - 'style'
      - 'refactor'
      - 'test'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
  default: patch
